#!/bin/bash
echo "📧 Email Confirmation Setup Helper"
echo ""
echo "Step 1: Get your Gmail App Password"
echo "   → Go to: https://myaccount.google.com/apppasswords"
echo "   → Generate a new App Password for 'Mail'"
echo "   → Copy the 16-character password"
echo ""
echo "Step 2: Update .env.local"
echo "   → Open .env.local in your editor"
echo "   → Find SMTP_PASSWORD=..."
echo "   → Replace with your new App Password"
echo ""
echo "Step 3: Restart server"
echo "   → Stop server (Ctrl+C)"
echo "   → Run: npm run dev"
echo ""
echo "Step 4: Test"
echo "   → Open browser console (F12)"
echo "   → Run the test command from EMAIL_SETUP_GUIDE.md"
echo ""
